import pyperclip, naturalsize

print("Willkommen beim Roadmap-Generator!")
print("Sie nutzen Version 2.0.1 (Copyright Leander Kafemann 2025)\n")

title = input("Titel der Roadmap: ")
num_steps = int(input("Wie viele Schritte/Milestones? "))

steps = []
for i in range(1, num_steps + 1):
    step_title = input(f"Titel fuer Schritt {i}: ")
    step_title = step_title.replace("ü", "&uuml;").replace("ä", "&auml;").replace("ö", "&ouml;").replace("ß", "&szlig;")
    step_title = step_title.replace("Ü", "&Uuml;").replace("Ä", "&Auml;").replace("Ö", "&Ouml;")
    step_desc = input(f"Beschreibung fuer Schritt {i}: ")
    step_desc = step_desc.replace("ü", "&uuml;").replace("ä", "&auml;").replace("ö", "&ouml;").replace("ß", "&szlig;")
    step_desc = step_desc.replace("Ü", "&Uuml;").replace("Ä", "&Auml;").replace("Ö", "&Ouml;")
    steps.append((step_title, step_desc))

html = f"""<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <title>{title}</title>
  <link rel="stylesheet" href="https://buero-os-toolkit-development.github.io/BueroWebKit/styling/style.css">
  <link rel="stylesheet" href="https://leanderkafemann.github.io/RoadmapAssistant/roadmap.css">
</head>
<body class="bwk-bg-neutral-100">
  <div class="bwk-container bwk-mt-5">
    <h1 class="bwk-text-center bwk-mb-4">{title}</h1>
    <div class="roadmap-wrapper">
      <h2>Roadmap</h2>
      <ol class="roadmap-list">
        <li class="roadmap-start">Status Quo</li>
"""

for idx, (step_title, step_desc) in enumerate(steps):
    html += """        <div class="roadmap-arrow">↓</div>
"""
    html += f"""        <li class="roadmap-step">
          <details>
            <summary>{step_title}</summary>
            <div class="step-desc">{step_desc}</div>
          </details>
        </li>
"""

html += """        <div class="roadmap-arrow">↓</div>
        <li class="roadmap-end">Ziel erreicht!</li>
      </ol>
    </div>
    <p class="small">
      Generated by RoadmapAssistant v2.0.1<br/>
      Copyright 2025 Leander Kafemann<br/>
      <a href="https://github.com/LeanderKafemann/RoadmapAssistant">&Uuml;ber RoadmapAssistant</a>
    </p>
  </div>
</body>
</html>
"""

print("HTML generiert und in die Zwischenablage kopiert:")
pyperclip.copy(html)
print(30*"-")
print(html)
print(30*"-")
if input("Als Datei exportieren (j/n)? ") == "j":
    with open("roadmap.html", "w", encoding="utf-8") as f:
        f.write(html)

print("Fertig!")
naturalsize.special_starter(75000000)